#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jan 03 16:01:00 MST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim riscv_cpu_tb_behav -key {Behavioral:sim_1:Functional:riscv_cpu_tb} -tclbatch riscv_cpu_tb.tcl -view /home/omar/Documents/projects/riscv-cpu/riscv-cpu/riscv_cpu_tb_behav.wcfg -log simulate.log"
xsim riscv_cpu_tb_behav -key {Behavioral:sim_1:Functional:riscv_cpu_tb} -tclbatch riscv_cpu_tb.tcl -view /home/omar/Documents/projects/riscv-cpu/riscv-cpu/riscv_cpu_tb_behav.wcfg -log simulate.log

